import { ExternalLink, FileSpreadsheet, RefreshCw } from "lucide-react";

const googleSheetUrl = "https://docs.google.com/spreadsheets/d/1NZM8v_hWtAh54GDy2A1r4kGog3LJyYynwEJvGdMt3E0/edit";

export function Operations() {
  return <main className="page-frame operations-page">
    <header className="page-header"><div><p className="eyebrow">Source and workflow</p><h1>Operations</h1><p className="page-description">How the Weekly Hub reads, preserves, and presents the SMART-MINDS records.</p></div><FileSpreadsheet className="page-header-icon" size={28} /></header>
    <section className="source-card"><div className="source-card-icon"><FileSpreadsheet size={20} /></div><div><p className="eyebrow">Authoritative archive</p><h2>Google Sheets</h2><p>The shared Google Doc is the live meeting workspace where students add updates and everyone discusses them together. The Meeting Database is the organized archive that the Hub reads through the Apps Script API. Students do not need to fill a second form for the current workflow.</p><a className="inline-link" href={googleSheetUrl} target="_blank" rel="noreferrer">Open the Google Sheet <ExternalLink size={14} /></a></div></section>
    <section className="operations-grid"><article><p className="eyebrow">Recommended workflow</p><h2>One update, one discussion space</h2><ol className="workflow-list"><li><strong>Shared Google Doc</strong><span>Students add their name, workstream, completed work, current work, next steps, and any question or support need under their own section.</span></li><li><strong>Simple progress status</strong><span>Use one small dropdown or label in the shared document: Done, In progress, or Blocked. Keep it next to the task so it is easy to scan during the meeting.</span></li><li><strong>Meeting Database</strong><span>After the meeting, preserve the organized record, source section, meeting date, task text, and status. This is what powers history and student portfolios.</span></li><li><strong>Weekly Hub</strong><span>Dr. Lina sees the current meeting as a one-row-per-update table, then opens Records or a student profile for the complete history.</span></li></ol></article><article><p className="eyebrow">Keep the fields simple</p><h2>What students should enter</h2><ul className="guidance-list"><li>Student name and workstream</li><li>What was completed</li><li>What is currently in progress</li><li>Next step or task</li><li>Progress: Done, In progress, or Blocked</li><li>Question or support needed, only when relevant</li></ul></article></section>
    <section className="operations-note"><RefreshCw size={17} /><div><strong>Refresh and archive behavior</strong><p>The Hub refreshes the Google Sheets source on load and periodically while open. The form route can remain available for a future workflow, but it is not required while the shared Google Doc is the team’s active update space. If the source is unavailable, the interface shows a clear retry state instead of an empty dashboard.</p></div></section>
  </main>;
}
