import { ExternalLink, FileSpreadsheet, RefreshCw } from "lucide-react";

const googleSheetUrl = "https://docs.google.com/spreadsheets/d/1NZM8v_hWtAh54GDy2A1r4kGog3LJyYynwEJvGdMt3E0/edit";

export function Operations() {
  return <main className="page-frame operations-page">
    <header className="page-header"><div><p className="eyebrow">Source and workflow</p><h1>Operations</h1><p className="page-description">How the Weekly Hub reads, preserves, and presents the SMART-MINDS records.</p></div><FileSpreadsheet className="page-header-icon" size={28} /></header>
    <section className="source-card"><div className="source-card-icon"><FileSpreadsheet size={20} /></div><div><p className="eyebrow">Authoritative source</p><h2>Google Sheets</h2><p>The Hub reads the meeting database, roster, and future Google Form responses through the Apps Script API. Google Sheets remains the system of record; this app does not use Supabase or invented demo records.</p><a className="inline-link" href={googleSheetUrl} target="_blank" rel="noreferrer">Open the Google Sheet <ExternalLink size={14} /></a></div></section>
    <section className="operations-grid"><article><p className="eyebrow">Data flow</p><h2>One source, several views</h2><ol className="workflow-list"><li><strong>Google Form Responses 1</strong><span>New student submissions remain preserved in the response sheet.</span></li><li><strong>Meeting Database</strong><span>Historical rows, meeting-level notes, tasks, questions, and source information stay organized.</span></li><li><strong>Apps Script API</strong><span>Normalizes headers and exposes updates plus the canonical student roster.</span></li><li><strong>Weekly Hub</strong><span>Meeting Review, Student Directory, and student history read the API data.</span></li></ol></article><article><p className="eyebrow">Field guidance</p><h2>What the app preserves</h2><ul className="guidance-list"><li>Student name and roster identity</li><li>Meeting date, including historical rows without a timestamp</li><li>Completed work, current work, and next steps</li><li>Questions, support needs, collaborators, and source links</li><li>Task text and task status</li><li>Source record ID, document, section, and attribution notes</li></ul></article></section>
    <section className="operations-note"><RefreshCw size={17} /><div><strong>Refresh behavior</strong><p>The app refreshes the Google Sheets source on load and periodically while open. If the source is unavailable, the interface shows a clear retry state instead of presenting an empty dashboard.</p></div></section>
  </main>;
}
